### ISSUE TITLE
Making a Custom Hwinfo64 Sensor?

### ISSUE THREAD

**Issue by dallebull** [Domi2803/HeartWear#6]
I'm trying to read the heartrate from the embedded link, but i aren't able to.
Misc. scraper addons for chrome doesn't work, "Invoke-WebRequest" doesn't seem to run the javescript so i can't log it with an powershell script either..

I want to save it to a txt file, use windows scheduler to look for changes and update an custom hwinfo sensor in regedit, i'd like to have my heartrate in my rtss overlay and aren't streaming with OBS..

**Comment by Domi2803** [comment]
You could request the data from the Firebase Database API directly to get the data in JSON.

First grab your uid, which is in the embed link: heartwear.web.app/(THIS IS YOUR UID)

And to use the Firebase API, send a GET Request to:
https://wearosheartrate-default-rtdb.europe-west1.firebasedatabase.app/(YOUR UID).json

You should receive a JSON object with a key called "currentHR". 

Hope that helps!

**Comment by dallebull** [comment]
Seems to work, sweet!
Thanks a lot!

**Comment by dallebull** [comment]
Got it working!
![image](https://user-images.githubusercontent.com/42966802/234822167-52a6e9a3-0897-4f57-8746-d1983c83722d.png)

**Comment by Domi2803** [comment]
Wow, that's looking nice! 😄 Glad I could help!
